# -*- coding: utf-8 -*-
"""connectomics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sugio6Lsp9WUxiH5DXpSxmIMikTj0zLz

# **`Process for getting CM`**
"""

!pip install nilearn
import nilearn as nl

"""**Checking if anat and fmri preprop data are good to create time series**"""

from nilearn import plotting, image
#checking dimensions of data - if 4, there's time series
str_img2 = "sub2_bold.nii"
str_img7 = "sub7_bold.nii"
#something about the square brackets messing things up with google colab; keeps
#us from misinterpreting
nl.EXPAND_PATH_WILDCARDS = False
fmri_obj2 = image.load_img(str_img2)
fmri_obj7 = image.load_img(str_img7)
print(fmri_obj2.shape, fmri_obj7.shape)

"""**Looking at func data first**"""

from nilearn.plotting import plot_stat_map, show
#visualising bold mask
for img in image.iter_img(str_img2):
  plot_stat_map(img, threshold = 3, display_mode = "x", cut_coords = [-10,0,10], colorbar = False)
  break

for img in image.iter_img(str_img7):
  plot_stat_map(img, threshold = 3, display_mode = "x", cut_coords = [-10,0,10], colorbar = False)
  break

"""**Checking parcellation of anat data**"""

# Load and display the parcellation file
parc_img2 = "sub2_parc.nii"
plotting.plot_roi(parc_img2, display_mode="x", cut_coords=[-10, 0, 10], cmap = "plasma", title="Parcellated Brain")
plotting.show()
nl.EXPAND_PATH_WILDCARDS = False
anat_obj2 = image.load_img(parc_img2)
print(anat_obj2.shape)

#-----------------------------------

parc_img7 = "sub7_parc.nii"
plotting.plot_roi(parc_img7, display_mode="x", cut_coords=[-10, 0, 10], cmap = "plasma", title="Parcellated Brain")
plotting.show()
nl.EXPAND_PATH_WILDCARDS = False
anat_obj7 = image.load_img(parc_img7)
print(anat_obj7.shape)

"""**getting names of our parecellated regions**"""

#getting parc label names for time series
import numpy as np
import json

with open("sub_2_dktlabel.json", "r") as f:
    labels2_file = json.load(f)

# regions actually covered in our parc file
unique_vals2 = np.unique(image.get_data(parc_img2))

# filter names based on what is in parc file
lab2_names = [entry["name"] for entry in labels2_file] # if entry["voxel_value"] in unique_vals
lab2_inds = [entry["label"] for entry in labels2_file if entry["voxel_value"] in unique_vals2]#string entries

print(len(lab2_names))
print(len(lab2_inds))

#print((unique_vals))
#label_inds.remove("0")
print(len(unique_vals2))

#--------------------------------

with open("sub_7_dktlabel.json", "r") as f:
    labels7_file = json.load(f)

# regions actually covered in our parc file
unique_vals7 = np.unique(image.get_data(parc_img7))

# filter names based on what is in parc file
lab7_names = [entry["name"] for entry in labels7_file] # if entry["voxel_value"] in unique_vals
lab7_inds = [entry["label"] for entry in labels7_file if entry["voxel_value"] in unique_vals7]#string entries

print(len(lab7_names))
print(len(lab7_inds))

#print((unique_vals))
#label_inds.remove("0")
print(len(unique_vals7))

"""**generating our time series data from our anat and func files**"""

# extracting time series with niftilabelsmasker
from nilearn.input_data import NiftiLabelsMasker
import matplotlib.pyplot as plt

masker2 = NiftiLabelsMasker(labels_img=anat_obj2, background_label= 0, standardize="zscore_sample")
masker2.fit()
masker2.generate_report()

#time series
time_series2 = masker2.fit_transform(fmri_obj2)
print(time_series2.shape)

#-------------------

masker7 = NiftiLabelsMasker(labels_img=anat_obj7, background_label= 0, standardize="zscore_sample")
masker7.fit()
masker7.generate_report()

#time series
time_series7 = masker7.fit_transform(fmri_obj7)
print(time_series7.shape)

"""**visualizing our time series from above**"""

#visualize fmri time series based on regions
np.random.seed(2004)

#num_regions = 5
selected_regions = np.array([17, 53, 8 , 47])

#np.random.choice(time_series2.shape[1], num_regions, replace=False)


#print(selected_regions2)
plt.figure(figsize=(10, 4))
for region in selected_regions:
    plt.plot(time_series2[:5, region], label= (lab2_names[region])+" - " + str(region)) #indexing based on og labels file; going up to 5 to match other

plt.xlabel('Time (TRs)')
plt.ylabel('Signal Intensity')
plt.title('Extracted Time Series; Subject 2 (Normal)')
plt.legend(prop={'size': 8})
plt.ylim(-3, 4)
plt.show()

#-------------------------

#num_regions = 5
#selected_regions7 = np.random.choice(time_series7.shape[1], num_regions, replace=False)

#print(selected_regions7)
plt.figure(figsize=(10, 4))
for region in selected_regions:
    plt.plot(time_series7[:, region], label= (lab7_names[region])+" - " + str(region)) #indexing based on og labels file

plt.xlabel('Time (TRs)')
plt.ylabel('Signal Intensity')
plt.title('Extracted Time Series; Subject 7 (Abnormal)')
plt.legend(prop={'size': 8})
plt.ylim(-3, 4)
plt.show()

"""**creating corr matrix for subject 2**"""

#finally cor matrix
# Compute the correlation matrix
corr_matrix2 = np.corrcoef(time_series2.T)  # Transpose so regions are along rows
corr_matrix2[np.abs(corr_matrix2) < 0.6] = 0 # thresholding
# Plot the connectivity matrix
plt.figure(figsize=(10, 4))
plt.imshow(corr_matrix2, cmap='coolwarm', vmin=-1, vmax=1)
plt.colorbar(label="Correlation")
plt.title("Functional Connectivity Matrix; Sub 2 (Normal)")
plt.xlabel("Brain Regions (0-108)")
plt.ylabel("Brain Regions (0-108)")
plt.show()

# there are 109 identified regions

#-----------------------------

corr_matrix7 = np.corrcoef(time_series7.T)  # Transpose so regions are along rows
corr_matrix7[np.abs(corr_matrix7) < 0.6] = 0 # thresholding
# Plot the connectivity matrix
plt.figure(figsize=(10, 4))
plt.imshow(corr_matrix7, cmap='coolwarm', vmin=-1, vmax=1)
plt.colorbar(label="Correlation")
plt.title("Functional Connectivity Matrix; Sub 7 (Abnormal)")
plt.xlabel("Brain Regions (0-108)")
plt.ylabel("Brain Regions (0-108)")
plt.show()